### ISSUE TITLE
Problem with Apostrophe

### ISSUE THREAD

**Issue by abitwhy** [antfu/vite-plugin-md#79] opened 2022-05-25 10:09 UTC
The encoded single quotation marks are inconsistent.

![screen_20220525_0852](https://user-images.githubusercontent.com/68452982/170238274-692f258c-ecd3-45c2-bb5d-a26494a5376e.png)

Here is a [reproduction project](https://stackblitz.com/edit/vitejs-vite-mtnsdt?file=src%2FApp.md).

**Comment by yankeeinlondon** [comment] 2022-05-31 20:25
can you provide a reproducible example: [example](https://vite.new/vue)

**Comment by yankeeinlondon** [comment] 2022-05-31 20:26
i'll have a look

**Comment by yankeeinlondon** [comment] 2022-05-31 20:30
looks like it probably is Markdown:
![image](https://user-images.githubusercontent.com/980757/171279064-a538a09d-d1f2-409e-a3fa-5f023888f44c.png)

https://markdown-it.github.io/

**Comment by yankeeinlondon** [comment] 2022-05-31 21:28
![2022-05-31_13-56-06 (1)](https://user-images.githubusercontent.com/980757/171284419-f7dd0e5a-74ea-4a8a-b80c-8954d492991a.gif)

ahhh ... ok it's a bit more complicated but the problem is related to [smart quotes](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/smartquotes.js) which is a feature many people want as it makes documents look a bit more professional. That's why the playground for markdown-it as well as this plugin turns on the "typographer" plugin by default. If you turned it off they would all be consistent but this may not be what you want.

You didn't state what part of this condition you were having problems but know that your last use case -- the bare use of `\'s` is _not_ considered a quotation mark based on grammer rules. It's simply a single quote followed by a character and therefore it will _never_ be converted to a quotation mark.

If you're current concern is regarding the first example where the text is wrapped in `<p>` tags. The first question is ... why would you do this in a Markdown document. This is normally done. If it's a code snippet then of course you should use the Markdown fence operator or wrap with `<pre>` as well. Alternatively some tags are treated differently, in fact I believe most tags are. You could substitute a `<div>` in it's place. But again, it's hard to understand why you'd want any of this as Markdown's equivalent to using the `<p>` tag is just adding a carraige return within the text corpus.

Ultimately however, you have a markdown-it issue if this is a true issue for you. I am going to close this but please re-open if you believe there is a good reason to.

**Closed by yankeeinlondon** 2022-05-31 21:28 UTC
