### ISSUE TITLE
Can I use this with nuxt for pages?

### ISSUE THREAD

**Issue by jd-0001** [antfu/vite-plugin-md#51] opened 2022-03-14 07:20 UTC
Hi,

I am building docs and I want to use markdown for each pages. I tried adding `button.md` in pages dir but with this plugin it shows:
```
[Vue Router warn]: No match found for location with path "/components/button"
[Vue warn]: Component  is missing template or render function.
```

my nuxt config:
```ts
export default defineNuxtConfig({
  modulesDir: ['../../node_modules'],
  vite: {
    plugins: [
      Vue({
        include: [/\.vue$/, /\.md$/], // <--
      }),
      Unocss({
        presets: [
          presetUno(),
        ]
      }),
      Markdown()
    ]
  },
})
```

**Comment by yankeeinlondon** [comment] 2022-03-27 23:42
I don't know Nuxt but if you're using ViteJS as your build system then it should work. The error you're getting seems to be trying to resolve a component called `button` in the _components_ folder. This would appear to NOT be related to the `button.md` file in your _pages_ directory.

**Comment by yankeeinlondon** [comment] 2022-04-21 21:18
i'm going to close this as I think this is not directly related to this plugin but if you feel it is then please re-open and give a reproducible example.

**Closed by yankeeinlondon** 2022-04-21 21:18 UTC
