### ISSUE TITLE
Dynamic props inside md tags?

### ISSUE THREAD

**Issue by rderimay** [antfu/vite-plugin-md#25] opened 2021-08-17 09:00 UTC
Hi.

I defined a .md component like this:

```
![]({{ path }})

<script setup>
import { defineProps } from "vue";

const props = defineProps({
  path: String,
});

const { path } = toRefs(props);
</script>
```

The goal is to pass the path as prop. The problem is that it renders as simple text and not as image tag, as I expected:

```
![](./images/image.jpg)
```

**Comment by antfu** [comment] 2021-08-18 03:15
Tried `<img :src="path"/>`? The markdown is parsed before Vue interpret it, the `{{}}` probably get escaped in your case.

**Comment by rderimay** [comment] 2021-08-20 07:36
That would be an easy fix of course :-)

My "problem" with this is that I apply a treatment to MD images though a custom renderer written as a `rules.image` in vite.
Adding `{{path}}` as src part in the MD, makes the image not even being recognized as image thus, not going through the custom rule renderer...

**Comment by antfu** [comment] 2021-08-20 08:08
Sorry I don't get it, any examples?

**Comment by rderimay** [comment] 2021-08-20 08:30
Yes sure.

I have a render method which, simplified, looks like this:

``` ts
md.renderer.rules.image = function (tokens, idx, options, env, self) {
    const token = tokens[idx]

    ...

    tokens[idx] = {
        type: 'inline',
        tag: 'LibImageLazyLoad',
        content: `
<LibImageLazyLoad>
    <img alt="${alt}" class="${className}" srcset="${src}?w=10&blur=1&format=jpg&space=srgb&metadata" style="display: none">
    <img alt="${alt}" class="${className}" srcset="${src}?${argsStr}">
</LibImageLazyLoad>`,

    ... 

    }

    // pass token to new renderer.
    return md.renderer.rules.html_inline(tokens, idx, options, env, self)
}

```

I would expect `![]({{ $path }}) to be recognized as image and be passed to this method, but this is not the case.

**Comment by yankeeinlondon** [comment] 2022-03-27 23:52
This looks like a question regarding **markdown-it** plugins and should probably be brought up there. Regardless, there's enough missing context here that you at minimum need to provide that. You mention the `![]({{ $path }})` as the source of the problem but it's not in your code example nor is there a clear definition of what the actual issue with this variable is? Is it uninitialized? 

Ultimately, this is why it's always a good idea to create a minimally reproducible example that people can look over to see the problem first hand. @rderimay can you get this issue into the proper state or should we close it?

**Comment by yankeeinlondon** [comment] 2022-04-21 21:18
Closing for now. @rderimay if you feel it should be open, please add a reproducible example that we can use as a reference.

**Closed by yankeeinlondon** 2022-04-21 21:18 UTC
